### ISSUE TITLE
Add Rotating Camera - missing

### ISSUE THREAD

**Issue by Dunravin** [JacquesLucke/Blender-Camera-Addon#4]
Hi Jacques,

Just playing with your great addon.

I have been watching your videos and notice there is an "Add Rotating Camera" button in your tool bar animation tab.

I'm using Sniper 1.3.2 on Blender 2.76b and I don't see this option. Was it removed or am I bugged?

Many thanks

**Comment by JacquesLucke** [comment]
I removed this function because it didn't fit in very well. 
I wanted to focus on the sniper camera :)

**Comment by Dunravin** [comment]
Ah ok, thanks for the quick reply :)
