### ISSUE TITLE
Doesn't work in 2.79?

### ISSUE THREAD

**Issue by lassipe** [JacquesLucke/Blender-Camera-Addon#7]
It says in header: "! Auto-run disabled [ignore] Driver 'var**2'

It creates camera targets and everything but the camera doesn't turn or move.

**Comment by JacquesLucke** [comment]
In the File settings in the user preferences you can enable Auto Run Python Scripts.

**Comment by lassipe** [comment]
Ok, thanks! This and animation nodes are great, thanks a lot for your awesome work!
