### ISSUE TITLE
Please add support for Blender 2.80

### ISSUE THREAD

**Issue by Almaz** [JacquesLucke/Blender-Camera-Addon#9]
Blender 2.80 is currently in Beta phase and API is almost stable. We should not expect any big changes anymore. It would be great if we could add support for this awesome plugin to Blender 2.80 as there is already a lot of users using it.

**Comment by tinogithub** [comment]
Yes, please. Would love to see it in action in 2.8, too.

**Comment by JacquesLucke** [comment]
I do not plan to update the addon to Blender 2.8 currently. However, I can give another developer commit access if you find one.

**Comment by tinogithub** [comment]
Hi Jacques, or maybe it can be done in animation node, too? The list of positions could be collected and then serve the camera. Just as I am thinking about it... I'll give it a try.
thank you. You do great work.

**Comment by tinogithub** [comment]
and yes. It is possible. :D AN is so versatile.
I love it.

**Comment by AntonioCaroppos** [comment]
@tinogithub I'm not sure if I understand your comment correctly. Are you going to try a conversion?

**Comment by schroef** [comment]
> and yes. It is possible. :D AN is so versatile.
> I love it.

COuld you put your repo online so we perhaps can test it?

**Comment by tinogithub** [comment]
@AntonioCaroppos and @schroef:
I built a node tree in animations nodes that acts similarly. Till now it collects some objects I want the camera to move to one after another. It can be improved but the logic works already.
